name: skilminedemo
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
#  skillmineauth: any
  skillmineauth:
    git:
      url: https://github.com/jatinkumarsahoo99/skillmineauth.git
      ref: main
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

